version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports :
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db && 
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=127.0.0.1
      - DB_NAME=django
      - DB_USER=joshy
      - DB_PASS=rrryyy123
    depends_on:
      - db 
  
  db:
    image: postgres:13-alpine
    volumes: 
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=joshy
      - POSTGRES_PAsSWORD=rrryyy123
      - POSTGRES_HOST_AUTH_METHOD=trust
  
volumes:
  dev-db-data: